project_id: '809432'
languages_mapping:
  two_letters_code:
    ja: ja
    en: en
base_path: .
base_url: 'https://api.crowdin.com'
preserve_hierarchy: 1
files:
  - source: /with-i18next-crowdin/src/locales/en/*.json
    translation: /with-i18next-crowdin/src/locales/%two_letters_code%/%original_file_name%
