#
# Basic Crowdin CLI configuration
# See https://crowdin.github.io/crowdin-cli/configuration for more information
# See https://support.crowdin.com/developer/configuration-file/ for all available options
#

#
# Your Crowdin credentials
#
"project_id": "809432"
"base_path": "."
"base_url": "https://api.crowdin.com"

#
# Defines whether to preserve the original directory structure in the Crowdin project
# Recommended to set to true
#
"preserve_hierarchy": true

#
# Files configuration.
# See https://support.crowdin.com/developer/configuration-file/ for all available options
#
files:
  [
    {
      "source": "/with-i18next-crowdin/src/locales/en/*.json",
      "translation": "/with-i18next-crowdin/src/locales/%two_letters_code%/%original_file_name%",
    },
  ]

languages_mapping:
  two_letters_code:
    ja: ja
    en: en
